const ingredients = [
  "Acetylated Lanolin",
  "Acetylated Lanolin Alcohol",
  "Algae Extract",
  "Algin",
  "Almond Oil",
  "Apricot Kernel Oil",
  "Argan Oil",
  "Avocado Oil",
  "Shea butter",
  "Coconut butter",
  "Almond butter",
  "butter",
  "Butyl Stearate",
  "C13-14 Isoparaffin",
  "Carrageenan",
  "Cetearyl Alcohol",
  "Ceteareth 20",
  "Cetyl Acetate",
  "Cheru Seed Oil",
  "Chlorella",
  "Chondrus Crispus",
  "Irish Moss",
  "Carageenan Moss",
  "Chullu Seed oil",
  "Wild Apricot Seed Oil",
  "Coal Tar",
  "Cocoa butter",
  "Coconut Alkanes",
  "Coconut Oil",
  "Colloidal Sulfur",
  "Corn Oil",
  "Cotton Awws Oil",
  "Cotton Seed Oil",
  "D & C Red # 17",
  "D & C Red # 21",
  "D & C Red # 3",
  "D & C Red # 30",
  "D & C Red # 36",
  "Decyl Oleate",
  "Dhupa Seed oil",
  "Dioctyl Succinate",
  "Disodium Monooleamido",
  "Ethoxylated Lanolin",
  "Ethylhexyl Palmitate",
  "Evening Primrose Oil",
  "Glyceryl Stearate SE",
  "Glyceryl-3 Diisostearate",
  "Groundnut Oil",
  "Hexadecyl Alcohol",
  "Hydrogenated Vegetable Oil",
  "Isocetyl Alcohol",
  "Isocetyl Stearate",
  "Isodecyl Oleate",
  "Isopropyl Isostearate",
  "Isopropyl Linolate",
  "Isopropyl Myristate",
  "Isopropyl Palmitate",
  "Isostearyl Isostearate",
  "Isostearyl Neopentanoate",
  "Kapok Oil",
  "Kasum Oil",
  "Kelp",
  "Kokum Oil",
  "Laminaria Digitata Extract",
  "Laminaria Saccharina",
  "Extract",
  "Lanolin",
  "Laureth – 23",
  "Laureth – 4",
  "Lauric Acid",
  "Mahua Seed oil",
  "Mink Oil",
  "Monostearate",
  "Myristic Acid",
  "Myristyl Alcohol",
  "Myristyl Lactate",
  "Myristyl Myristate",
  "Nahor Seed Oil",
  "Neem Oil",
  "Octyl Palmitate",
  "Octyl Stearate",
  "Oleth – 3",
  "Oleth – 5",
  "Oleyl Alcohol",
  "Olive Oil",
  "Palash Oil",
  "Palm Kernel Oil",
  "Palm Oil",
  "Peach Kernel Oil",
  "Peanut Oil",
  "PEG 100 Distearate",
  "PEG 150 Distearate",
  "PEG 200 Dilaurate",
  "PEG – 16",
  "PEG 16 Lanolin",
  "PEG2 – Sulfosuccinate",
  "PEG 8 Stearate",
  "PG Monostearate",
  "Pilu Oil",
  "Pisu Oil",
  "PPG 2 Myristyl Propionate",
  "Plankton",
  "Polyglyceryl – 3",
  "Diisostearate",
  "Polyglyceryl – Diisostearate",
  "Potassium Chloride",
  "Monostearate",
  "PPG 2 Myristyl Propionate",
  "Propylene Glycol Monostearate",
  "Ratanjyat Oil",
  "Red Algae",
  "Brown Algae",
  "Rice Bran Oil",
  "Sal Seed Oil",
  "Sea Whip Extract",
  "Seaweed",
  "Sesame Oil",
  "Shark Liver Oil (Squalene)",
  "Sodium Carbomer",
  "Shea Butter",
  "Sodium Laureth Sulfate",
  "Sodium Lauryl Sulfate",
  "Solulan 16",
  "Sorbitan Oleate",
  "Soybean Oil",
  "Spirulina",
  "Steareth – 10",
  "Steareth – 2",
  "Stearic Acid Tea",
  "Stearyl Heptanoate",
  "Sulfated Castor Oil",
  "Sulfated Jojoba Oil",
  "Tribeheniin",
  "Undi Oil",
  "Wheat Germ Glycerides",
  "Wheat Germ Oil",
  "Xylene"
];

export default ingredients;
